### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by lucapette** [lucapette/fakedata#44]
#43 is an exciting change to `fakedata` UI but, as @kevingimbel pointed out, it's a breaking change and we agreed it's a good idea to aim for a first stable version.

Here is what i have in mind at the moment:

- [x] [New syntax for generators](https://github.com/lucapette/fakedata/issues/39)  
- [x] [Proposal: Template functionality](https://github.com/lucapette/fakedata/issues/45)
- [x] [Validating and parsing all the options once before the generation starts](https://github.com/lucapette/fakedata/pull/48). I think this is a bit complicated to achieve give the current design
- [x] [--format should return an error if the format isn't known ](https://github.com/lucapette/fakedata/issues/20) 
- [x] [dictionary generator](https://github.com/lucapette/fakedata/issues/30) 
- [x] [Explain why fakedata differs from other tools](https://github.com/lucapette/fakedata/issues/16) plus a general restructuring of the README (I'll open a specific issue for that that incoporates #16 too)
- [x] Review the existing generators and remove as much as possible

Completing all the features/fixes of this list should give us a pretty solid (and nicely featured) `fakedata v1.0.0`. I'll be tagging the existing issues accordingly so we get a better overview of what's done and what needs to be done.

About #17 and #30, I know @kevingimbel and @jorinvo respectively offered to help with those. Both features aren't easy to implement so I'm thinking I can take care of the rest while we shape those two complicated features.

Suggestions about what to add/remove from `v1.0.0` are always _more_ than welcome!

[Here](https://github.com/lucapette/fakedata/milestone/1) is the up to date milestone `v1.0.0`

**Comment by kevingimbel** [comment]
@lucapette How do we handle documentation? All inside the README.md for now? Or should we add a Wiki to the project?

I would like to start documenting the new template feature but I don't know where to put it.

**Comment by lucapette** [comment]
@kevingimbel I would keep it in the README for now. I suggest you add a section about templates in the readme. As soon as we land all the features we have been working on, we'll rethink it a bit because we're outgrowing the current structure (which is great!)

**Comment by kevingimbel** [comment]
@lucapette I checked the Template functionality off the list since it's been merged. 

Now what's open is the "Explain why fakedata differs" part.

**Comment by lucapette** [comment]
@kevingimbel thank you for taking care of it! I'm working on making the template feature work together with #48 it's not the easiest merge :) As soon as I'm done with that I open a pr for the reorganization of the README and then we cut the v1.0.0. Nice release coming!

**Comment by lucapette** [comment]
@kevingimbel thank you for taking care of it! I'm working on making the template feature work together with #48 it's not the easiest merge :) As soon as I'm done with that I open a pr for the reorganization of the README and then we cut the v1.0.0. Nice release coming!

**Comment by lucapette** [comment]
I've just shipped #48 to master with a disclaimer in the docs about the breaking changes. I'll open a PR about the re-organization of the readme and then I say we're good to go for version 1.0.0!

**Comment by kevingimbel** [comment]
@lucapette big up! These changes look really good. :)

**Comment by lucapette** [comment]
I pushed a draft of the new README #50 so we can start discussing there. I added a final check point to this issue so we can discuss which generators we intend to support in version 1.0.0. But I think it's better we do that in a separate issue. I'll take care of creating it!

**Comment by lucapette** [comment]
Done! I've just released version 1.0.0. Very happy with what we have! 🎉
